name: CI

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            target: x86_64-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Raylib 5.5
        run: |
          wget -q https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_linux_amd64.tar.gz
          tar -xzf raylib-5.5_linux_amd64.tar.gz
          echo "RAYLIB=$PWD/raylib-5.5_linux_amd64" >> $GITHUB_ENV

      - name: Check Raylib
        run: |
          ls -la "$RAYLIB/include"
          ls -la "$RAYLIB/lib"

      - name: Download and build Zen C
        run: |
          git clone https://github.com/zen-lang/zenc
          cd zenc
          git checkout a3a4698dc78fce99acbde01eab640e0753a94116
          make clean
          make ZC_HAS_JIT=0
          make install PREFIX="$GITHUB_WORKSPACE/zenc-install"
          echo "ZC_ROOT=$GITHUB_WORKSPACE/zenc-install/share/zenc" >> "$GITHUB_ENV"
          echo "$GITHUB_WORKSPACE/zenc-install/bin" >> "$GITHUB_PATH"

      - name: Check Zen C
        run: |
          ls -la "$ZC_ROOT"
          zc --version
